name: "Auto Merge Dependabot"

on:
  pull_request_target:
    types: [ opened, ready_for_review, reopened]

jobs:
  auto-merge-dependabot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.REPO_ACCESS_TOKEN }}