name: "Build and Push"
on:
  push: 
    branches:
      - main    

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '12.x'
    - name: NPM iunstall
      run: npm install
    - name: NPM run all
      run: npm run all
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "[dcAG infrastructure] Build"
        commit_user_name: dcAG infrastructure
        commit_user_email: infrastructure@dc.ag
        commit_author: dcAG infrastructure <infrastructure@dc.ag>
